soak_time: 12h
pre_steam_drain_time: 10m
steam_time: 60m
cool_time: 10m
drain_time: 10m
dry_time: 30m
wait_for_human_input_time: 20m
incubate_time: 36h
incubate_temp: 88F
slack: 1
interval_time: 1s
unit: F
phone_number: 8184553749
