soak_time: 1s
pre_steam_drain_time: 1s
steam_time: 1s
cool_time: 1s
drain_time: 1s
dry_time: 1s
wait_for_human_input_time: 1s
incubate_time: 10s
incubate_temp: 88F
slack: 1
interval_time: .0001s
unit: F
phone_number: 8184553749
pwm_freq: 2
pid_Kp: 1.0
pid_Ki: 0.1
pid_Kd: 0.05
checkpoint_length: 1
history_file: '~/.auto_fermenter_history'
